research_task:
  description: >
    Conduct a thorough research on the given marketing data
    Make sure you find any interesting and relevant information that can be used to make interesting social media post or email newsletter
    Facebook, Instagram, X.com, Threads and email newsletters - these are the platforms that we will use for social media
  expected_output: >
    Detailed information about topics that can be used as material for posts or email newsletters


trend_analys_task:
  name: "Trend Analysis Task"
  description: >
    Conduct a thorough research about trends in social media now.
    Make sure to find any important information about how to make viral posts on Facebook, Instagram, X.com, Threads, and email newsletters.
    Include popular tags where relevant.
  expected_output: >
    A list of points about the different platforms with 10 bullet points of the most relevant information about the trends on the given platform.
  input_format: "text"
  output_format: "structured_list"
  required_tools:
    - WebSearchTool
    - OutputFileTool

trend_analysis_report_task:
  name: "Trend Analysis Report Task"
  description: >
    Use the collected data to produce a detailed report summarizing the current trends and strategies for viral content.
  expected_output: >
    A structured report that includes key insights, popular tags, and actionable strategies for each platform.
  input_format: "file_path"
  output_format: "text_summary"
  required_tools:
    - FileReadTool
    - TextProcessingTool

# instagram agent tools

instagram_supervise_task:
  description: >
    Coordinate the process of creating an Instagram post. Review research data, guide the writer and editor,
    and ensure the final post is suitable for publication.
  expected_output: >
    An organized post-creation process with a high-quality, approved Instagram post and an image prompt for DALL-E 3.

instagram_write_post_task:
  description: >
    Draft an engaging Instagram post based on the provided research and trend data.
  expected_output: >
    A well-written Instagram post draft that aligns with the marketing strategy.

instagram_edit_post_task:
  description: >
    Review the post draft for errors, brand consistency, and platform suitability.
    Provide feedback or approve for the final stage.
  expected_output: >
    An edited and approved Instagram post ready for finalization.

instagram_generate_image_prompt_task:
  description: >
    Create a detailed prompt for DALL-E 3 to generate an Instagram-worthy image.
    Align the image prompt with the finalized post content.
  expected_output: >
    A prompt that generates a visually appealing, context-appropriate image (1024x1024) for Instagram.