research_task:
  description: >
    Conduct a thorough research on the given marketing data
    Make sure you find any interesting and relevant information that can be used to make interesting social media post or email newsletter
    Facebook, Instagram, X.com, Threads and email newsletters - these are the platforms that we will use for social media
  expected_output: >
    Detailed information about topics that can be used as material for posts or email newsletters


trend_analys_task:
  name: "Trend Analysis Task"
  description: >
    Conduct a thorough research about trends in social media now.
    Make sure to find any important information about how to make viral posts on Facebook, Instagram, X.com, Threads, and email newsletters.
    Include popular tags where relevant.
  expected_output: >
    A list of points about the different platforms with 10 bullet points of the most relevant information about the trends on the given platform.
  input_format: "text"
  output_format: "structured_list"
  required_tools:
    - WebSearchTool
    - OutputFileTool

trend_analysis_report_task:
  name: "Trend Analysis Report Task"
  description: >
    Use the collected data to produce a detailed report summarizing the current trends and strategies for viral content.
  expected_output: >
    A structured report that includes key insights, popular tags, and actionable strategies for each platform.
  input_format: "file_path"
  output_format: "text_summary"
  required_tools:
    - FileReadTool
    - TextProcessingTool
# trend_analys_task:
#   description: >
#     Conduct a thorough research about trends in social media now
#     Make sure you find any important information about how to make viral posts on Facebook, Instagram, X.com, Threads and email newsletters
#     the more information the better
#   expected_output: >
#     A list of points about the different platforms with 10 bullet points of the most relevant information about the trends on the given platform