research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formated as markdown with out '```'
trend_analys_task:
  description: >
    Conduct a thorough research about trends in social media now
    Make sure you find any important information about how to make viral posts on Facebook, Instagram, X.com, Threads and email newsletters
    the more information the better
  expected_output: >
    A list of points about the different platforms with 10 bullet points of the most relevant information about the trends on the given platform